apiVersion: v1
kind: ReplicationController
metadata:
  name: simon-says
spec:
  replicas: 5
  template:
    metadata:
      labels:
        role: simon-says-server
        version: "0.1"
    spec:
      containers:
      - name: simon-says
        image: gcr.io/${PROJECT}/server
        imagePullPolicy: Always
        env:
          - name: REDIS_ADDRESS
            value: redis:6379
        ports:
        - containerPort: 50051